"""add like model

Revision ID: 389add41e70f
Revises: bddc0ef5e7ac
Create Date: 2024-12-27 00:47:21.771385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389add41e70f'
down_revision: Union[str, None] = 'bddc0ef5e7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('liker', sa.UUID(), nullable=False),
    sa.Column('liked', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['liked'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liker'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liked'),
    sa.UniqueConstraint('liker')
    )
    op.add_column('users', sa.Column('telegram_short_link', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_short_link')
    op.drop_table('likes')
    # ### end Alembic commands ###
