"""remove unique

Revision ID: edb8e45a44f3
Revises: fa4c0b7ae4d9
Create Date: 2024-12-28 02:57:06.010983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb8e45a44f3'
down_revision: Union[str, None] = 'fa4c0b7ae4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likes_liked_key', 'likes', type_='unique')
    op.drop_constraint('likes_liker_key', 'likes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('likes_liker_key', 'likes', ['liker'])
    op.create_unique_constraint('likes_liked_key', 'likes', ['liked'])
    # ### end Alembic commands ###
